//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ConnectManager.h
//  @ Date : 2012/12/7
//  @ Author :
//
//


#if !defined(_CONNECTMANAGER_H)
#define _CONNECTMANAGER_H

#include "MessageIdentifiers.h"

#include "RakPeerInterface.h"
#include "RakNetStatistics.h"
#include "RakNetTypes.h"
#include "BitStream.h"
#include "PacketLogger.h"
#include <assert.h>
#include <cstdio>
#include <cstring>
#include <string>
#include <stdlib.h>
#include "RakNetTypes.h"

#include "Kbhit.h"
#include "WindowsIncludes.h" // Sleep
#include "DancingGuiSys.h"
#include "Gets.h"
#include "DancingHouse.h"
#include <iostream>
using namespace std;
unsigned char GetPacketIdentifier(RakNet::Packet *p);
enum CUSTOM_MESSAGE_ID_TYPE//CustomMessageIDType
{
    /*******************************************************************
    * 说    明：此枚举用于网络通信类型的标识，例如客户端请求房间类表或服务器发送类表等
                           且RAKNET网络引擎本身也维护了一个类似的枚举，且结束于DefaultMessageIDTypes
    					   DefaultMessageIDTypes在RAKNET的值排到了129，故此处枚举值从130开始
    * 作    者： grius
    * 日    期：2013年3月21日
    *******************************************************************/
    CS_GET_HOUSES_LIST = 130,//用于局域网模式客户端向服务器请求房间列表
    SC_GET_HOUSES_LIST ,//用于局域网模式服务器向客户端发送房间列表

    CS_CREATE_HOUSE,//用于局域网模式客户端向服务器请求创建房间
    SC_CREATE_HOUSE,//用于局域网模式服务器向客户端通知新房间创建成功



    CS_LOGOFF_HOUSE,//用于局域网模式客户端向服务器申请退出某房间
    SC_LOGOFF_HOUSE,//用于局域网模式服务器向客户端通知某某退出某房间

    CS_LOGIN_HOUSE,//用于局域网模式客户端向服务器申请加入某房间
    /*******************************************************************
    * 说    明：因为我用的传送消息，一到一定次数就会失效，目前先把下面这条消息分做两次发送
    * 作    者： grius
    * 日    期：2013年3月21日
    *******************************************************************/
    SC_LOGIN_HOUSE_ONE,//用于局域网模式服务器向客户端通知某某加入某房间
    SC_LOGIN_HOUSE_TWO,//用于局域网模式服务器向客户端通知某某加入某房间
    SC_LOGIN_HOUSE_TO_OTHERONE,//用于局域网模式服务器向房间内另一客户端通知某某加入房间

    CS_READY,
    SC_READY,

    CS_UNREADY,
    SC_UNREADY,



    /*******************************************************************
    * 说    明：由于房间列表目前是客户端主动请求（每隔一段时间请求一次），故此不必通知客户端某某房间已经不再了
                           建议添加一些出错信息的处理,如网络过度拥塞的情况，有的请求会变质，但目前先不费精力去做此处
    					   类似于房间重名，角色重名，房间位置不够等信息都在客户端进行检测
    * 作    者： grius
    * 日    期：2013年3月21日
    *******************************************************************/
};

/*******************************************************************
* 说    明：此类为单例模式
* 作    者： grius
* 日    期：2013年3月21日
*******************************************************************/
class ConnectManager
{
    //for singleton
private:
    ConnectManager(void);
    ~ConnectManager(void);
    static ConnectManager *instance;
public:
    static ConnectManager *GetInstance();//get the singleton pointer

public:
    void ConfigClient(void); //config sever`s some info
    void StartUpClient(void);//starup the sever

    void Send(string tempstring, string tempstring2 = ""); //use for send message   ,it will appear in a main loop
    void Receive(void);//use for receive message   ,it will appear in a main loop

    void handleHouseList(RakNet::BitStream *);
    void handleNewHouseRequest();
    void handleLoginRequsetOne(RakNet::BitStream *);
    void handleLoginRequsetTwo(RakNet::BitStream *);
    void handleOtherRoleJoin(RakNet::BitStream *);
    void handleOtherRoleLeave();
    void handleReady();
    void handleUnReady();


private:

    RakNet::RakPeerInterface *m_clientPtr;//"raknet"`s kernel object
    RakNet::Packet *m_packetPtr;//

    unsigned char m_packetIdentifier;//the massage`s identify,  联系枚举CUSTOM_MESSAGE_ID_TYPE
    RakNet::SystemAddress m_clientID;//a variable can indentify client

    char m_ip[64], m_serverPort[30], m_clientPort[30];


    //对应于文件顶部的结构体
    RakNet::MessageID mTypeId; // This will be assigned to a type I've added after ID_USER_PACKET_ENUM, lets say ID_SET_TIMED_MINE

};

#endif  //_CONNECTMANAGER_H
