/*
-----------------------------------------------------------------------------
Filename:    BoneAnim.h
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.7.x Application Wizard for VC9 (August 2010)
      http://code.google.com/p/ogreappwizards/
-----------------------------------------------------------------------------
*/
#ifndef __BoneAnim_h_
#define __BoneAnim_h_

#include "BaseApplication.h"
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#include "../res/resource.h"
#endif


class BoneAnim : public BaseApplication
{
public:
    BoneAnim(void);
    virtual ~BoneAnim(void);

protected:
    virtual void createScene(void);

//xuyunhan*****************************************************************************************

	void createSkeletonAnimation(void);//创建骨骼动画,在createScene里调用
	void createManuallyControlledBone(Ogre::String boneName);//创建手动控制的骨骼,名字为boneName

	bool frameStarted(const Ogre::FrameEvent& evt);
};

#endif // #ifndef __BoneAnim_h_
